# Site settings
title: 火焰彩虹 | Gao
email: In_Energy@163.com
description: 感恩生活,珍惜拥有
# > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  momeakl
permalink: /:year/:month/:day/:title/
# excerpt
excerpt_separator: "\n\n\n\n"
# Build settings
markdown: kramdown
paginate: 6
paginate_path: "page:num"
#highlighter: pygments
# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false




